<a href="https://colab.research.google.com/github/Josema1304/C8280/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas


Pandas es un paquete Python de código abierto que proporciona estructuras de datos rápidas, flexibles y expresivas diseñadas para que trabajar con datos "relacionales" o "etiquetados" sea fácil e intuitivo.

### Estructuras de datos
Pandas presenta dos nuevas estructuras de datos en Python: Series y DataFrame, ambas construidas sobre NumPy (esto significa que es rápido).


#### Serie

Este es un objeto unidimensional similar a la columna en una hoja de cálculo o tabla SQL. De forma predeterminada, a cada elemento se le asignará una etiqueta de índice de `0` a `N`. 

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
s = pd.Series([1,3,4,np.nan, 5, 6], index = ['A', 'B', 'C', 'D', 'E', 'F'])
print(s)

A    1.0
B    3.0
C    4.0
D    NaN
E    5.0
F    6.0
dtype: float64


Si creas una serie utilizando el diccionario, la clave se convertirá en el índice de forma predeterminada. 

In [7]:
dict_ejemplo = {'A': 1, 'B':2, 'C':3, 'D':np.nan, 'E': 5, 'F': 6}
dict_ejemplo

{'A': 1, 'B': 2, 'C': 3, 'D': nan, 'E': 5, 'F': 6}

In [8]:
s = pd.Series(dict_ejemplo)
print(s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


La contraparte bidimensional de las series unidimensionales es el DataFrame.

### DataFrame

Es un objeto bidimensional similar a una hoja de cálculo o una tabla SQL. Este es el objeto Pandas más utilizado. 


In [9]:
data = {'Genero': ['F', 'M', 'M'],
        'Emp_ID': ['E01', 'E02', 'E03'],
        'Edad': [25, 27, 25]}
# Si queremos el orden de las columnas, especificamos en el parametro columns
df = pd.DataFrame(data, columns=['Emp_ID', 'Genero', 'Edad'])
df 

Emp_ID Genero  Edad
0    E01      F    25
1    E02      M    27
2    E03      M    25

#### Lectura y escritura de datos 

Veremos tres formatos de archivo de uso común: csv, archivo de texto y Excel. 

In [34]:
# Lectura de un archivo csv
df = pd.read_csv('mtcars.csv')
df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [35]:
# Escribir un csv
# index = False - no escribe los valores de indice, el valor predeterminado es True 
# completar
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'Name': ['John', 'Emma', 'Peter'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

df = pd.DataFrame(data)

# Escribir el DataFrame en un archivo CSV
df.to_csv('output.csv', index=False)


In [36]:
# Leyendo desde un archivo .txt
# df=pd.read_csv('Data/mtcars.txt', sep='\t')
# completar
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['John', 'Emma', 'Peter'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

df = pd.DataFrame(data)

# Write the DataFrame to a CSV file
df.to_csv('output.csv', index=False)


In [38]:
# Leyendo un archivo Excel
#df=pd.read_excel('Data/mtcars.xlsx','Sheet2')
# Completar
import pandas as pd

# Reading an Excel file
df = pd.read_excel('mtcars.xlsx', sheet_name='Sheet2')


### Resumen de estadísticas básicas


In [40]:
#df = pd.read_csv('Data/iris.csv')
# completar
import pandas as pd

# Reading a CSV file
df = pd.read_csv('iris.csv')


#### Covarianza
 

In [41]:
# covarianza: devuelve la covarianza entre columnas adecuadas 
# completar
import pandas as pd

# Create a sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [1, 3, 5, 7, 9]
}

df = pd.DataFrame(data)

# Calculate the covariance
cov_matrix = df.cov()

print(cov_matrix)


     A    B     C
A  2.5 -2.5   5.0
B -2.5  2.5  -5.0
C  5.0 -5.0  10.0


#### Correlación


In [42]:
# completar
import pandas as pd

# Create a sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [1, 3, 5, 7, 9]
}

df = pd.DataFrame(data)

# Calculate the correlation
corr_matrix = df.corr()

print(corr_matrix)


     A    B    C
A  1.0 -1.0  1.0
B -1.0  1.0 -1.0
C  1.0 -1.0  1.0


### Visualización de datos
Pandas DataFrame viene con funciones integradas para ver los datos contenidos: 

* Mirando los `n` primeros registros, el valor predeterminado de `n` es 5 si no se especifica:  `df.head(n=2)`.

* Mirando los `n` registros inferiores: `df.tail()`

* Obtener los nombres de las columnas: `df.columns`

* Obtener los tipos de datos de las columnas: `df.types`

* Obtener el índice del dataframe: `df.index`

* Obtener valores únicos: `df[column_name].unique()`

* Obtener valores: `df.values`

* Ordenar el dataframe: `df.sort_values(by =['Column1', 'Column2'], ascending=[True,True'])`

* Seleccionar/ver por el nombre de la columna: `df[column_name]`

* Seleccionar/ver por número de fila `df[0:3]`

* Selección por índice: 

- `df.loc[0:3] # índice de 0 a 3` 
- `df.loc[0:3,[‘column1’, ‘column2’]] # índice de 0 a 3 para las columnas específicas`

* Selección por posición

- `df.iloc[0:2] # usando el rango, primeras 2 filas` 
- `df.iloc[2,3,6] # posición específica`
-  `df.iloc[0:2,0:2] # primeras 2 filas y primeras 2 columnas`

* Selección sin que esté en el índice

- `print(df.ix[1,1]) # valor de la primera fila y la primera columna` 
- `print(df.ix[:,2]) # todas las filas de la columna en la segunda posición`

* Alternativa más rápida a `iloc` para obtener valores escalares: `print(df.iat[1,1])`

* Transponer el dataframe: `df.T`

* Filtrar DataFrame según la condición de valor para una columna: `df[df['column_name'] > 7.5]`

* Filtrar DataFrame basado en una condición de valor en una columna: `df[df['column_name'].isin(['condition_value1', 'condition_value2'])]`

* Filtro basado en múltiples condiciones en múltiples columnas usando el operador AND: `df[(df['column1']>7.5) & (df['column2']>3)]`

* Filtro basado en múltiples condiciones en múltiples columnas usando el operador OR: `df[(df[‘column1’]>7.5) | (df['column2']>3)]`. 

In [44]:
# print ("Nombres de las columnas:" , df.columns)
import pandas as pd

# Assuming df is the DataFrame variable
print("Column names:", df.columns)

Column names: Index(['A', 'B', 'C'], dtype='object')


In [45]:
# print ("Indice del DataFrame : ", df.index)
import pandas as pd

# Assuming df is the DataFrame variable
print("DataFrame index:", df.index)


DataFrame index: RangeIndex(start=0, stop=5, step=1)


In [47]:
# print(df.values)
import pandas as pd

# Assuming df is the DataFrame variable
print(df.values)

[[1 5 1]
 [2 4 3]
 [3 3 5]
 [4 2 7]
 [5 1 9]]


In [ ]:
# Valores para una especifica columna
# Completar

In [ ]:
# df['Species'].unique()

In [ ]:
# df['Sepal.Length'].unique()

In [ ]:
# df.sort_values(by = ['Species', 'Sepal.Length'], ascending=[True, True])

In [ ]:
#df['Species']

In [ ]:
# completar

Selección diferente por opciones de etiqueta

- `loc:` solo funciona en el índice
- `iloc:` trabaja en posición
- `iat:` Obtener valores escalares. es un `iloc` muy rapido. 

In [ ]:
# selección por indice
# completar

In [ ]:
# selección por indice de nombres de etiquetas específicas
# completar

In [ ]:
# Selección por posición
# completar

In [ ]:
# Seleccion por posicion entre filas dadas como rango
# completar

**Ejercicio**

¿Qué produce `df.iloc[0:3, 0:3]` ?

In [ ]:
## Tu respuesta

In [ ]:
# seleccion por posicion entre numeros de fila especificos dados
# Completar

Selección por índice de fila y columna (el índice comienza con 0). 

El siguiente caso obtendrá el valor `[índice de la primera fila, índice de la primera columna]`.

In [ ]:
# obtener valores escalares. es un iloc muy rapido 
# print(df.iat[1,1]) 

In [ ]:
# Obtencion de datos sin que este en el indice 
#print(df.iloc[1,1])

In [ ]:
# selecciona columnas por posicion
#print (df.iloc[:, 2]) 

In [ ]:
# Transpuesta
# df.T

#### Indexado Booleano

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

### Operaciones básicas con Pandas

* Convertir cadenas a series de fechas: `pd.to_datetime(pd.Series(['2017-04-01','2017-04-02','2017-04-03']))`.

* Cambiar el nombre de una columna específica: `df.rename(columns={‘old_columnname’:‘new_columnname'}, inplace=True)`

* Cambiar el nombre de todas las columnas del DataFrame: `df.columns = ['col1_new_name','col2_new_name'...]`

* Marcar duplicados: `df.duplicated()`

* Quitar duplicados:`df = df.drop_duplicates()`

* Quitar duplicados en una columna específica: `df.drop_duplicates(['column_name'])`

* Quitar los duplicados en una columna específica, pero se conserva la primera o la última observación en el conjunto de duplicados: `df.drop_duplicates(['column_name'], keep = 'first') # cambiar al ultimo para conservar la ultima observación del duplicado`.

* Crear una nueva columna a partir de una columna existente: `df['new_column_name'] = df['new_column_name'] + 5`

* Crear una nueva columna a partir de los elementos de dos columnas: `df['new_column_name'] = df['existing_column1'] + '_' + df['existing_column2']`

* Agregar una lista o una nueva columna a DataFrame: `df['new_column_name'] = pd.Series(mylist)`

* Descartar las filas y columnas faltantes que tienen valores faltantes: `df.dropna()`

* Reemplaza todos los valores faltantes con 0 (o puede usar cualquier int o str): `df.fillna(value=0)`

* Reemplaza los valores faltantes con la última observación válida (útil en datos de series de tiempo). Por ejemplo, la temperatura no cambia drásticamente en comparación con una observación anterior. Una forma es llenar de NA forward-backward más alla de la media.

    1) 'pad' / 'ffill' - forward fill

    2) 'bfill'/'backfill' - backward fill

    Límite: si se especifica el método, este es el número máximo de valores de NaN consecutivos para completar forward/backward fill: `df.fillna (method = 'ffill', inplace= True, limit = 1)`

* Verifica la condición del valor faltante y devuelva el valor Booleano de `True` o `False` para cada celda: `pd.isnull(df)`

* Reemplaza todos los valores faltantes para una columna dada con la media: `mean=df['column_name].mean(); df['column_name'].fillna(mean)`

* Devuelve la media para cada columna: `df.mean()`

* Retorna el máximo para cada columna: `df.max()`

* Retorno el mínimo para cada columna: `df.min()`

* Devuelve la suma para cada columna: `df.sum()`

* Conteo para cada columna: `df.count()`

* Devuelve la suma acumulada para cada columna: `df.cumsum()`

* Aplica una función a lo largo de cualquier eje del DataFrame: `df.apply(np.cumsum)`

* Itera sobre cada elemento de una serie y realizar la acción deseada: `df['column_name'].map(lambda x: 1+x) # esto itera sobre la columna y agrega el valor 1 a cada elemento`

* Aplica una función a cada elemento del dataframe:`func = lambda x: x + 1 # función para agregar una constante 1 a cada elemento del dataframe df.applymap(func)`. 

In [ ]:
cadena_fechas = ('2017-04-01','2017-04-02','2017-04-03','2017-04-04')
pd.to_datetime(pd.Series(cadena_fechas))

In [ ]:
#df.rename(columns = {'Sepal.Length': 'Sepal_Length'}, inplace=True)

In [ ]:
#df.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Species']


In [ ]:
# Removemos los duplicados

data_1 = {'primer_nombre': ['Amy', 'Amy', 'Jason', 'Nick', 'Stephen','Amy'],
        'ultimo_nombre': ['Jackson', 'J', 'Miller', 'Milner', 'L','J'],
        'edad': [42, 42, 36, 24, 24, 42]}
df = pd.DataFrame(data_1, columns = ['primer_nombre', 'ultimo_nombre', 'edad'])
print(df)

In [ ]:
#print(df.duplicated())

In [ ]:
# print(df.drop_duplicates())

In [ ]:
#df.drop_duplicates(['primer_nombre'], keep ='first')

**Ejercicio**

* Agrega las columnas siguientes: `edad_mas_5`, `nombre_completo` y `genero`
 - `edad_mas_5`viene de sumar 5 a la etiqueta `edad`
 - `nombre_completo` viene de sumar las etiquetas `primer_nombre`, `_` y `ultimo_nombre`
 - `genero` es una serie de elementos `'F','F','M','M','M','F'.`

In [ ]:
# Tu respuesta

#### Datos perdidos

pandas usa principalmente el valor `np.nan` para representar los datos que faltan. Por defecto no se incluye en los cálculos. 

In [ ]:
#df.iloc[4,2] = np.nan
#print(df)

In [ ]:
#print(df.dropna())

In [ ]:
#df.iloc[4,2] = np.nan
#print(df)

In [ ]:
#df.fillna(value =0)

In [ ]:
#df.iloc[4,2] = np.nan
#print(df)

In [ ]:
#pd.isnull(df)

#### Operaciones

In [ ]:
#media = df['edad'].mean()
#media
# usamos la media para reeemplazar el NaN
# completar 

In [ ]:
# df.fillna(method='ffill', inplace=True, limit=1)

In [ ]:
#import warnings
#warnings.filterwarnings('ignore')
#df.mean()

In [ ]:
#df.min()

In [ ]:
#df.max()

In [ ]:
#df.sum()

In [ ]:
#df.count()

In [ ]:
#df.cumsum()

#### Aplicación de función a elemento, columna o dataframe


In [ ]:
# completar

In [ ]:
# Map: itera sobre cada elemento de una serie
# Completar agrega una constante 1 a cada elemento de la column1


In [ ]:
#func=lambda x: x+1
#df_filtrado = df.iloc[:, 2:4]
#print(df_filtrado)

In [ ]:
#print(df_filtrado.applymap(func))

**Ejemplo**

La parte del poder de pandas se da por los métodos integrados en los objetos Series y DataFrame. 

In [ ]:
from io import StringIO
data = StringIO('''UPC,Units,Sales,Date
1234,5,20.2,1-1-2014
1234,2,8.,1-2-2014
1234,3,13.,1-3-2014
789,1,2.,1-1-2014
789,2,3.8,1-2-2014
789,,,1-3-2014
789,1,1.8,1-5-2014''')

In [ ]:
sales = pd.read_csv(data)
sales

In [ ]:
sales.shape

In [ ]:
sales.info()

A diferencia del objeto `Series` que prueba la pertenencia con el índice, el `DataFrame` prueba la pertenencia con las columnas. El comportamiento de iteración `(__iter__)` y el comportamiento de pertenencia `(__contains__)` es el mismo para el `DataFrame`.  

#### Operaciones de índice


In [ ]:
# sales.reindex([0, 4])

In [ ]:
#sales.reindex(columns=['Date', 'Sales']) 

La selección de columnas e índices se puede combinar para refinar aún más la selección. Además, se pueden incluir nuevas entradas para valores de índices y nombres de columna. Por defecto, usarán el parámetro opcional `fill_value` (que es NaN a menos que se especifique): 

In [ ]:
#sales.reindex(index=[2, 6, 8], columns=['Sales', 'MIT', 'missing'])

In [ ]:
#by_date = sales.set_index('Date')
#by_date

Para agregar un índice entero creciente a un data frame, usa `.reset_index`: 

In [ ]:
# by_date.reset_index()

#### Obtener y establecer valores


In [ ]:
#sales.iat[4, 2]


A continuación, insertamos una columna `Category` después de ` UPC`  (en la posición 1): 

In [ ]:
#sales.insert(1, 'Category', 'Food')
# sales

El método `.replace` es una forma poderosa de actualizar muchos valores de un data frame en las columnas. Para reemplazar todos los 789 con 790, realiza lo siguiente:

In [ ]:
# sales.replace(789, 790)

In [ ]:
#sales.replace({'UPC': {789:790},
#                'Sales': {789: 1.4}})

El método `replace` también acepta expresiones regulares (pueden ser incluidas en diccionarios anidados) si  el paramétro`regex` se coloca en `True`.

In [ ]:
#sales.replace('(F.*d)', r'\1_stuff', regex=True)

#### Eliminación de  columnas

Hay al menos cuatro formas de eliminar una columna:

* El método `.pop`

* El método `.drop` con `axis = 1`

* El método `.reindex`

* Indexación con una lista de nuevas columnas

El método `.pop` toma el nombre de una columna y lo elimina del data frame. Opera in-place. En lugar de devolver un data frame, devuelve la columna eliminada.  

In [ ]:
#sales['subcat'] = 'Dairy'
#sales

In [ ]:
# sales.pop('subcat')

In [ ]:
#sales

Para quitar una columna con el método `.drop`, simplemente páselo (o una lista de nombres de columna) junto con la configuración del parámetro `axis` en 1: 

In [ ]:
# completar

#### Los dos métodos finales para eliminar columnas

In [ ]:
#cols = ['Sales', 'Date']

In [ ]:
# sales.reindex(columns=cols)

In [ ]:
#sales[cols]

#### Recortes


In [ ]:
#sales.head()

In [ ]:
#sales.tail(2)

Usemos un índice basado en cadenas para que quede más claro qué hacen las opciones de recorte:

In [ ]:
# completar

In [ ]:
# del sales['new_index']

In [ ]:
# df

Para dividir por posición, usa el atributo `.iloc`. Aquí tomamos filas en las posiciones dos hasta cuatro, pero sin incluirlas: 

In [ ]:
#df.iloc[2:4]

También podemos proporcionar posiciones de columna que también queremos mantener. Las posiciones de las columnas deben seguir una coma en la operación de índice. Aquí mantenemos las filas desde dos hasta pero sin incluir la fila cuatro. También tomamos columnas desde cero hasta pero sin incluir uno (solo la columna en la posición de índice cero).

Esto se expresa en la siguiente figura:


<img src="recorte-pandas.png" alt="Drawing" style="width: 500px;"/>

A continuación se muestra un resumen de las construcciones de  de data frame por posición y etiqueta.


```
.iloc [i: j]            Posición de filas i hasta pero sin incluir j (semiabierto)
.iloc [:, i: j]         Posición de las columnas i hasta pero sin incluir j (semiabierto)
.iloc [[i, k, m]]       Filas en i, k y m (no es un intervalo)
.loc [a: b]             Filas desde la etiqueta de índice a hasta b (cerrado)
.loc [:, c: d]          Columnas de la etiqueta de columna c a d (cerrado)
.loc [: [b, d, f]]      Columnas en las etiquetas b, d y f (no es un intervalo) 

```

<img src="recorte-ejemplo.png" alt="Drawing" style="width: 600px;"/>

In [ ]:
#df = df.drop(['Category'], axis=1)
#df

In [ ]:
# df.iloc[2:4, 0:1]

También hay soporte para dividir datos por etiquetas. Usando el atributo `.loc`, podemos tomar valores de índice desde la `a` a la `d`:

In [ ]:
# completar

Y al igual que `.iloc`, `.loc` tiene la capacidad de especificar columnas por etiqueta. En este ejemplo, solo tomamos la columna `Units` y, por lo tanto, devuelve una serie:

In [ ]:
# completar

Sacamos las columnas `UPC` y `Sales`, pero con solo los últimos 4 valores:

In [ ]:
# Completar

### Merge/Join


In [ ]:
data = {
        'emp_id': ['1', '2', '3', '4', '5'],
        'primer_nombre': ['Jason', 'Andy', 'Allen', 'John', 'Amy'], 
        'ultimo_nombre': ['Larkin', 'Jacob', 'A', 'AA', 'Jackson']}
df_1 = pd.DataFrame(data, columns = ['emp_id', 'primer_nombre', 'ultimo_nombre'])
print (df_1)

In [ ]:
data = {
        'emp_id': ['4', '5', '6', '7'],
        'primer_nombre': ['James', 'Shize', 'Kim', 'Jose'], 
        'ultimo_nombre': ['Alexander', 'Suma', 'Mike', 'G']}
df_2 = pd.DataFrame(data, columns = ['emp_id', 'primer_nombre', 'ultimo_nombre'])
print (df_2)

In [ ]:
# usando concat
df = pd.concat([df_1, df_2])
print(df)

In [ ]:
# Juntando dos dataframes a lo largo de las columnas
pd.concat([df_1,df_2], axis=1)

Combinamos dos dataframes basados en el valor `emp_id` en este caso, solo se unirán los `emp_id` presentes en ambas tablas.

In [ ]:
print(pd.merge(df_1,df_2, on='emp_id'))

### Grouping


Pandas nos brinda la capacidad de agrupar data frames por valores de columna y luego fusionarlos nuevamente en un resultado con el método `.groupby`.
Pandas `group by` nos permitirá lograr lo siguiente:

- Aplicar una función de agregación a cada grupo de forma independiente
- Según algunos criterios, divide los datos en grupos.
- Combinar los resultados del `group by` en una estructura de datos.


<img src="Groupby.png" alt="Drawing" style="width: 700px;"/>

Como ejemplo, en el data frame `scores`, calcularemos las puntuaciones medias de cada maestro. Primero llamamos a `.groupby` y entonces invocamos a `.median` en el resultado: 

In [ ]:
#scores = pd.DataFrame({
#    'name':['Adam', 'Bob', 'Dave', 'Fred'],
#    'age': [15, 16, 16, 15],
#    'test1': [95, 81, 89, None],
#    'test2': [80, 82, 84, 88],
#    'teacher': ['Ashby', 'Ashby', 'Jones', 'Jones']})

In [ ]:
# completar

Esto incluyó la columna `age`, para ignorar que podemos separar solo las columnas de prueba: 

In [ ]:
# completar

Para encontrar los valores medianos de cada grupo de edad para cada maestro, simplemente agrupa por maestro y edad: 


In [ ]:
# completar

Si queremos los puntajes mínimos y máximos de las pruebas por maestro, usamos el método `.agg` y pasamos una lista de funciones para llamar: 

In [ ]:
# completar

**Ejercicio**

In [ ]:
df = pd.DataFrame({'Nombre' : ['jack', 'jane', 'jack', 'jane', 'jack', 'jane', 'jack', 'jane'],
                   'Estado' : ['SFO', 'SFO', 'NYK', 'CA', 'NYK', 'NYK', 'SFO', 'CA'],
                   'Genero':['A','A','B','A','C','B','C','A'],
                   'Edad' : np.random.uniform(24, 50, size=8),
                   'Salario' : np.random.uniform(3000, 5000, size=8),})

Ten en cuenta que las columnas se ordenan automáticamente en su orden alfabético para un orden personalizado, usa el siguiente código_

`df = pd.DataFrame (data, columns = ['Nombre', 'Estado', 'Edad', 'Salario'])` 

* Calcula la suma por nombres.

* Encuentra la edad máxima y el salario por nombre/ estado. Puedes usar todas las funciones agregadas, como mínimo, máximo, media, conteo, suma acumulada.

In [ ]:
# Tus  respuestas

#### Tablas pivot

Pandas proporciona una función `pivot_table` para crear una tabla pivot (dinámica )de estilo de hoja de cálculo de MS-Excel. Puede tomar los siguientes argumentos:

- `data`: objeto DataFrame
- `values`: columna para agregar
- `index`: etiquetas de fila
- `columns`: etiquetas de columna
- `aggfunc`: función de agregación que se usará en valores, el valor predeterminado es `NumPy.mean`. 

Usando una tabla pivot, podemos generalizar ciertos comportamientos grupales. Para obtener las puntuaciones medias de los profesores, podemos ejecutar lo siguiente: 

In [ ]:
# completar

Si queremos agregar por maestro y edad, simplemente usamos una lista con ambos para el parámetro `index`: 

In [ ]:
#scores.pivot_table(index=['teacher', 'age'],
#                   values=['test1', 'test2'],
#                   aggfunc='median')

Si queremos aplicar múltiples funciones, simplemente usa una lista de ellas. Aquí, analizamos los puntajes mínimos y máximos de las pruebas por maestro: 

In [ ]:
#scores.pivot_table(index='teacher',
#                   values=['test1', 'test2'],
#                   aggfunc=[min, max])

Podemos ver que la tabla pivot y de grupo por comportamiento son muy similares. Hay del estilo declarativo de `.pivot_table` y el estilo  semántico de los grupos.

Una característica adicional de las tablas pivots es la capacidad de agregar filas de resumen. Simplemente estableciendo `margins= True` obtenemos esta funcionalidad:

In [ ]:
#scores.pivot_table(index='teacher',
#                   values=['test1', 'test2'],
#                   aggfunc='median', margins=True)

<img src="pivot.png" alt="Drawing" style="width: 700px;"/>

In [ ]:
#scores.pivot_table(index= ['teacher', 'age'],
#                   values=['test1', 'test2'],
#                   aggfunc=[len, sum], margins=True)

<img src="pivot-parameters.png" alt="Drawing" style="width: 700px;"/>

**Ejercicio** Del dataframe anterior agrupa por estado y nombre y encuentre la edad media para cada grado.


In [ ]:
## Tu respuesta